# =================================
# RabbitMQ Deployment
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # ?∏ÌîÑ??Ïª¥Ìè¨?åÌä∏Î°?Í∞Ä??Î®ºÏ? ?§Ìñâ
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: petful-secrets
                  key: rabbitmq-username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: petful-secrets
                  key: rabbitmq-password

---
# =================================
# Redis Deployment
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # ?∏ÌîÑ??Ïª¥Ìè¨?åÌä∏Î°?Í∞Ä??Î®ºÏ? ?§Ìñâ
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis:7
          ports:
            - containerPort: 6379
          command: ["redis-server"]
          args: ["--requirepass", "$(REDIS_PASSWORD)"]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petful-secrets
                  key: redis-password

---
# =================================
# frontend Deployment
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petful-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petful-frontend
  template:
    metadata:
      labels:
        app: petful-frontend
    spec:
      containers:
        - name: petful-frontend-container
          image: gyongcode/petful-frontend:v0.0.33
          ports:
            - containerPort: 3000

---
# =================================
# Config Service
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Í∞Ä??Î®ºÏ? ?§Ìñâ
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service-container
          image: gyongcode/petful-config-service:v0.0.25
          volumeMounts:
            - name: keystore-volume
              mountPath: "/app/secrets"
              readOnly: true
          ports:
            - containerPort: 8888
          env:
            - name: SSH_KEY
              valueFrom:
                secretKeyRef:
                  name: config-service-secrets
                  key: SSH_KEY

            - name: KEYSTORE_PATH
              value: "/app/secrets/petful-api.jks"

            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-service-secrets
                  key: KEYSTORE_PASSWORD
            - name: KEY_ALIAS
              valueFrom:
                secretKeyRef:
                  name: config-service-secrets
                  key: KEY_ALIAS
          # # Health Check Ï∂îÍ?
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8888
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8888
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
      volumes:
        - name: keystore-volume
          secret:
            secretName: keystore-secrets

---
# =================================
# Discovery Service (Eureka)
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Config Service ?§Ïùå???§Ìñâ
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service-container
          image: gyongcode/petful-discovery-service:v0.0.25
          ports:
            - containerPort: 8761
          env:
            - name: CONFIG_SERVER_URI
              value: "http://config-service:8888"
          # # Health Check Ï∂îÍ?
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8761
          #   initialDelaySeconds: 90
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8761
          #   initialDelaySeconds: 60
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          #   failureThreshold: 3

---
# =================================
# Gateway Service (API Gateway)
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Discovery Service ?§Ïùå???§Ìñâ
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service-container
          image: gyongcode/petful-gateway-service:v0.0.25
          ports:
            - containerPort: 8000
          env:
            - name: CONFIG_SERVER_URI
              value: "http://config-service:8888"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka"
          # # Health Check Ï∂îÍ?
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8000
          #   initialDelaySeconds: 120
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8000
          #   initialDelaySeconds: 90
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          #   failureThreshold: 3

---
# =================================
# Business Services
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "3" # Gateway Service ?§Ïùå???§Ìñâ
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service-container
          image: gyongcode/petful-user-service:v0.0.25
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CONFIG_SERVER_URI
              value: "http://config-service:8888"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka"
          # # Health Check Ï∂îÍ?
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8081
          #   initialDelaySeconds: 120
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8081
          #   initialDelaySeconds: 90
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          #   failureThreshold: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-service-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-service
  template:
    metadata:
      labels:
        app: pet-service
    spec:
      containers:
        - name: pet-service-container
          image: gyongcode/petful-pet-service:v0.0.25
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CONFIG_SERVER_URI
              value: "http://config-service:8888"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka"
          # # Health Check Ï∂îÍ?
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8082
          #   initialDelaySeconds: 120
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8082
          #   initialDelaySeconds: 90
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          #   failureThreshold: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-service-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: community-service
  template:
    metadata:
      labels:
        app: community-service
    spec:
      containers:
        - name: community-service-container
          image: gyongcode/petful-community-service:v0.0.25
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CONFIG_SERVER_URI
              value: "http://config-service:8888"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka"
          # # Health Check Ï∂îÍ?
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8083
          #   initialDelaySeconds: 120
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8083
          #   initialDelaySeconds: 90
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          #   failureThreshold: 3

---
# =================================
# Advertiser Service
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advertiser-service-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: advertiser-service
  template:
    metadata:
      labels:
        app: advertiser-service
    spec:
      containers:
        - name: advertiser-service-container
          image: gyongcode/petful-advertiser-service:v0.0.25
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CONFIG_SERVER_URI
              value: "http://config-service:8888"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka"
          # # Health Check Ï∂îÍ?
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8084
          #   initialDelaySeconds: 120
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8084
          #   initialDelaySeconds: 90
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          #   failureThreshold: 3

---
# =================================
# Campaign Service
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign-service-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: campaign-service
  template:
    metadata:
      labels:
        app: campaign-service
    spec:
      containers:
        - name: campaign-service-container
          image: gyongcode/petful-campaign-service:v0.0.25
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CONFIG_SERVER_URI
              value: "http://config-service:8888"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka"
          # # Health Check Ï∂îÍ?
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8085
          #   initialDelaySeconds: 120
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8085
          #   initialDelaySeconds: 90
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          #   failureThreshold: 3

---
# =================================
# Health Service
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-service-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-service
  template:
    metadata:
      labels:
        app: health-service
    spec:
      containers:
        - name: health-service-container
          image: gyongcode/petful-health-service:v0.0.25
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CONFIG_SERVER_URI
              value: "http://config-service:8888"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka"
          # # Health Check Ï∂îÍ?
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8086
          #   initialDelaySeconds: 120
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8086
          #   initialDelaySeconds: 90
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          #   failureThreshold: 3

---
# =================================
# Notification Service
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service-container
          image: gyongcode/petful-notification-service:v0.0.25
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CONFIG_SERVER_URI
              value: "http://config-service:8888"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka"

          # # Health Check Ï∂îÍ?
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8087
          #   initialDelaySeconds: 120
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8087
          #   initialDelaySeconds: 90
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          #   failureThreshold: 3

---
# =================================
# SNS Service
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sns-service-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sns-service
  template:
    metadata:
      labels:
        app: sns-service
    spec:
      containers:
        - name: sns-service-container
          image: gyongcode/petful-sns-service:v0.0.25
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CONFIG_SERVER_URI
              value: "http://config-service:8888"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka"
          # # Health Check Ï∂îÍ?
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8088
          #   initialDelaySeconds: 120
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8088
          #   initialDelaySeconds: 90
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          #   failureThreshold: 3
