# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petful-frontend-deployment # 디플로이먼트의 이름
spec:
  replicas: 2 # 안정성을 위해 Pod를 2개 실행
  selector:
    matchLabels:
      app: petful-frontend # 이 라벨을 가진 Pod들을 관리
  template:
    metadata:
      labels:
        app: petful-frontend # Pod에 붙일 라벨
    spec:
      containers:
        - name: petful-frontend-container
          # ⬇️ Jenkins가 빌드 후 이 부분을 새 이미지 태그로 업데이트합니다.
          image: gyongcode/petful-frontend:v1.0.1
          ports:
            - containerPort: 3000 # Next.js 앱이 사용하는 포트
